#!/usr/bin/env python3
"""Build a Russian (Cyrillic) codepage variant of FONT16.TIM for the PC port.

The PSX font atlas has 84 glyph slots ('..z, indices 0..83) drawn as 12x16 cells.
Cyrillic can't fit alongside Latin, so for the Russian locale we swap the whole
atlas: keep the digits, space and a few punctuation glyphs in place, and fill the
remaining 67 slots with the 66 Cyrillic letters. The localization engine then
transliterates each Cyrillic code point to the byte that indexes its slot, so the
existing renderer draws Russian with no engine/VRAM changes.

Inputs : the original FONT16.TIM (extracted from the disc) + a Cyrillic TTF.
Outputs: Assets/Locales/Russian/Font16.tim  (the swapped atlas, same format)
         pc_port/include/pc_locale_cyrillic.h (codepage map + glyph widths)
         a preview PNG.
"""
import os, struct, sys
from PIL import Image, ImageFont, ImageDraw

HERE = os.path.dirname(__file__)
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))

GLYPH_W, GLYPH_H = 12, 16
COLS = 21  # glyphs per tpage page
OFFSET = 0x27  # byte of slot 0 ("'")

# Original 84 glyph advance widths (from text_draw.c FONT_12X16_GLYPH_WIDTHS).
ORIG_WIDTHS = [
    3,7,7,11,11,4,10,4,6,10,10,10,10,10,10,10,10,10,10,4,4,10,11,10,8,13,12,12,12,13,11,11,
    13,12,9,9,12,12,13,12,13,11,13,12,10,11,13,12,12,12,11,12,6,4,6,8,0,3,9,10,9,9,9,7,11,11,
    6,6,10,6,13,11,10,11,10,8,8,7,10,10,12,10,10,9
]

# Slots we KEEP from the original atlas (byte -> meaning). Everything else is free
# for Cyrillic. Space is slot 56 (byte '_'), handled by the renderer, left blank.
KEEP_BYTES = set(b"0123456789.,-?")       # digits + essential punctuation
KEEP_BYTES |= {ord('_')}                  # space (renderer advances, glyph unused)
KEEP_BYTES |= {ord('['), ord(']')}        # menu selection cursor brackets

CYR_UPPER = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ"   # 33
CYR_LOWER = "абвгдеёжзийклмнопрстуфхцчшщъыьэюя"   # 33


def slot_x(i):
    return (i // COLS) * 256 + (i % COLS) * GLYPH_W


def decode_font16(path):
    data = open(path, "rb").read()
    p = 8
    clutlen = struct.unpack('<I', data[p:p+4])[0]
    clut = data[p+12:p+12+16*2]; p += clutlen
    ilen = struct.unpack('<I', data[p:p+4])[0]
    iw, ih = struct.unpack('<HH', data[p+8:p+12])
    pix = data[p+12:p+12+ilen-12]
    # grayscale level (0..15) per pixel
    lvl = [[0]*(iw*4) for _ in range(ih)]
    for y in range(ih):
        for xw in range(iw):
            w = struct.unpack('<H', pix[(y*iw+xw)*2:(y*iw+xw)*2+2])[0]
            for n in range(4):
                lvl[y][xw*4+n] = (w >> (n*4)) & 0xF
    return clut, lvl, iw*4, ih


def build():
    clut, base, W, H = decode_font16(os.path.join(_scratch(), "FONT16.TIM"))
    # New atlas levels, start as a copy of the original.
    out = [row[:] for row in base]
    widths = ORIG_WIDTHS[:]

    free = [i for i in range(84) if (OFFSET + i) not in KEEP_BYTES and i != 56]
    cyr = list(CYR_UPPER) + list(CYR_LOWER)
    assert len(cyr) <= len(free), f"{len(cyr)} cyr > {len(free)} free slots"

    font = ImageFont.truetype(os.path.join(_fonts(), "NotoSans-Bold.ttf"), 15)
    codepage = {}  # cyrillic char -> byte
    for ch, slot in zip(cyr, free):
        # Rasterize the glyph centered in a 12x16 cell, antialiased.
        cell = Image.new("L", (GLYPH_W, GLYPH_H), 0)
        d = ImageDraw.Draw(cell)
        bb = font.getbbox(ch)
        gw, gh = bb[2]-bb[0], bb[3]-bb[1]
        ox = (GLYPH_W - gw)//2 - bb[0]
        oy = (GLYPH_H - gh)//2 - bb[1] + 1
        d.text((ox, oy), ch, fill=255, font=font)
        x0 = slot_x(slot)
        for y in range(GLYPH_H):
            for x in range(GLYPH_W):
                out[y][x0 + x] = cell.getpixel((x, y)) >> 4  # 0..255 -> 0..15
        widths[slot] = min(GLYPH_W, max(gw + 2, 6))
        codepage[ch] = OFFSET + slot

    _write_tim(out, clut, W, H, os.path.join(_ru_dir(), "Font16.tim"))
    _write_header(widths, codepage)
    _write_preview(out, clut, W, H)
    print(f"[cyrillic] placed {len(cyr)} glyphs into {len(free)} free slots")
    print(f"[cyrillic] wrote Assets/Locales/Russian/Font16.tim, pc_locale_cyrillic.h, preview")


def _write_tim(lvl, clut, W, H, path):
    iw = W // 4
    pix = bytearray()
    for y in range(H):
        for xw in range(iw):
            w = 0
            for n in range(4):
                w |= (lvl[y][xw*4+n] & 0xF) << (n*4)
            pix += struct.pack('<H', w)
    body = bytearray()
    body += struct.pack('<I', 0x10) + struct.pack('<I', 0x08)        # magic + flag (4bpp+CLUT)
    body += struct.pack('<I', 12 + 32) + struct.pack('<HHHH', 0, 0, 16, 1) + clut
    body += struct.pack('<I', 12 + len(pix)) + struct.pack('<HHHH', 0, 0, iw, H) + bytes(pix)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "wb").write(body)


def _write_header(widths, codepage):
    lines = ["#ifndef PC_LOCALE_CYRILLIC_H", "#define PC_LOCALE_CYRILLIC_H", "",
             "/* Generated by pc_port/tools/build_cyrillic_font.py — do not edit. */", "",
             "/* Advance widths for the Russian codepage atlas (Assets/Locales/Russian/Font16.tim). */",
             "static const unsigned char RU_GLYPH_WIDTHS[84] = {"]
    for i in range(0, 84, 12):
        lines.append("    " + ", ".join(str(w) for w in widths[i:i+12]) + ",")
    lines.append("};")
    lines.append("")
    lines.append("/* Cyrillic code point (U+0410..U+044F incl. Ё/ё) -> atlas slot byte. */")
    lines.append("typedef struct { unsigned short cp; unsigned char byte; } s_CyrMap;")
    lines.append("static const s_CyrMap RU_CODEPAGE[] = {")
    order = list(CYR_UPPER) + list(CYR_LOWER)
    for ch in order:
        lines.append(f"    {{ 0x{ord(ch):04X}, 0x{codepage[ch]:02X} }}, /* {ch} */")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* PC_LOCALE_CYRILLIC_H */")
    open(os.path.join(REPO, "pc_port", "include", "pc_locale_cyrillic.h"), "w",
         encoding="utf-8").write("\n".join(lines) + "\n")


def _write_preview(lvl, clut, W, H):
    pal = []
    for i in range(16):
        w = struct.unpack('<H', clut[i*2:i*2+2])[0]
        pal.append((((w & 31) << 3), (((w >> 5) & 31) << 3), (((w >> 10) & 31) << 3)))
    atlas = Image.new("RGB", (W, H))
    for y in range(H):
        for x in range(W):
            atlas.putpixel((x, y), pal[lvl[y][x]])
    # Render a sample sentence using the codepage, for a human check.
    order = list(CYR_UPPER) + list(CYR_LOWER)
    free = [i for i in range(84) if (OFFSET + i) not in KEEP_BYTES and i != 56]
    cp = {ch: free[k] for k, ch in enumerate(order)}
    sample = "НАЧАТЬ ПРОДОЛЖИТЬ ЗАГРУЗКА НАСТРОЙКИ ВЫХОД"
    sw = sum((GLYPH_W if c != ' ' else 6) for c in sample)
    line = Image.new("RGB", (sw, H), (0, 0, 0)); x = 0
    for c in sample:
        if c == ' ': x += 6; continue
        slot = cp.get(c)
        if slot is None: x += GLYPH_W; continue
        x0 = slot_x(slot)
        for yy in range(H):
            for xx in range(GLYPH_W):
                line.putpixel((x+xx, yy), pal[lvl[yy][x0+xx]])
        x += GLYPH_W
    out = Image.new("RGB", (max(W, sw), H*2+4), (20, 20, 30))
    out.paste(atlas, (0, 0)); out.paste(line, (0, H+4))
    out = out.resize((out.width*2, out.height*2), Image.NEAREST)
    out.save(os.path.join(_scratch(), "cyrillic_font_preview.png"))


def _scratch():
    return r"C:\Users\yeezy01\AppData\Local\Temp\claude\D--silent-dev\bb15be0c-a7ae-44ba-9741-9fc8b110f276\scratchpad"
def _fonts():
    return os.path.join(_scratch(), "SilentEngine", "Assets", "Fonts")
def _ru_dir():
    return os.path.join(REPO, "pc_port", "Assets", "Locales", "Russian")


if __name__ == "__main__":
    build()
