#!/usr/bin/env python3
"""Build ONE unified Unicode font atlas for the PC port (SilentEngine-style).

Instead of swapping an 84-glyph atlas per language, we build a single atlas that
holds the base ASCII set PLUS every non-ASCII glyph the shipped locales use
(European accents + Cyrillic), all rasterized from NotoSans-Bold. The renderer
decodes UTF-8 and indexes glyphs by code point, so all languages render from one
atlas with no per-locale swap and no transliteration.

VRAM: the framebuffers end at Y480, FONT16 sits at (0,496). We use a 256x32 atlas
at (0,480): the bottom 16px row is the base ASCII set (slots 0..83, drawn at
v=240 like the stock font); the top 16px row holds the extended glyphs (slots
84+, drawn at v=224). 84 extra slots — enough for Cyrillic + common accents.

Outputs:
  pc_port/Assets/font/Font16Unified.tim   (256x32 atlas uploaded at boot)
  pc_port/include/pc_glyphmap.h            (widths[168] + code point -> slot)
"""
import os, struct, glob, json
from PIL import Image, ImageFont, ImageDraw

HERE = os.path.dirname(__file__)
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
GLYPH_W, GLYPH_H, COLS, OFFSET = 12, 16, 21, 0x27
EXT_BASE = 84            # first extended slot index
EXT_MAX  = 84            # extended capacity (one 16px row)

def scratch():
    return r"C:\Users\yeezy01\AppData\Local\Temp\claude\D--silent-dev\bb15be0c-a7ae-44ba-9741-9fc8b110f276\scratchpad"

def slot_uv(i):
    """Atlas (image-x, image-y) for a logical slot. Each 21-glyph block sits in a
    separate 256px tpage column (renderer uses idx/21 -> tpage, idx%21 -> u).
    Base 0..83 -> image bottom (y16); extended 84+ -> image top (y0)."""
    if i < EXT_BASE:
        return (i // COLS) * 256 + (i % COLS) * GLYPH_W, 16
    e = i - EXT_BASE
    return (e // COLS) * 256 + (e % COLS) * GLYPH_W, 0

FONT = None
def raster(ch):
    cell = Image.new("L", (GLYPH_W, GLYPH_H), 0)
    if ch != ' ':
        d = ImageDraw.Draw(cell)
        bb = FONT.getbbox(ch)
        d.text((1 - bb[0], GLYPH_H - 3 - bb[3]), ch, fill=255, font=FONT)
    lv = [[cell.getpixel((x, y)) >> 4 for x in range(GLYPH_W)] for y in range(GLYPH_H)]
    if ch == ' ':
        return lv, 6
    return lv, max(3, min(GLYPH_W, int(round(FONT.getlength(ch))) + 1))

def load_clut():
    data = open(os.path.join(scratch(), "FONT16.TIM"), "rb").read()
    return data[20:20+32]  # 16 * 2 bytes, right after the 12-byte CLUT header at p=8

def used_codepoints():
    """Every non-ASCII code point appearing in any shipped Locale.json value."""
    cps = set()
    for p in glob.glob(os.path.join(REPO, "pc_port", "Assets", "Locales", "*", "Locale.json")):
        for v in json.load(open(p, encoding="utf-8")).values():
            for c in v:
                if ord(c) >= 0x80:
                    cps.add(ord(c))
    return sorted(cps)

def main():
    global FONT
    FONT = ImageFont.truetype(os.path.join(scratch(), "SilentEngine", "Assets", "Fonts", "NotoSans-Bold.ttf"), 14)

    # 168 logical slots: 0..83 base ASCII, 84+ extended.
    levels = [None] * (EXT_BASE + EXT_MAX)
    widths = [0] * (EXT_BASE + EXT_MAX)
    for i in range(EXT_BASE):
        ch = ' ' if i == 56 else chr(OFFSET + i)
        levels[i], widths[i] = raster(ch)

    cps = used_codepoints()
    if len(cps) > EXT_MAX:
        print(f"[warn] {len(cps)} extended glyphs > {EXT_MAX} slots; truncating")
        cps = cps[:EXT_MAX]
    codepage = []
    for k, cp in enumerate(cps):
        slot = EXT_BASE + k
        levels[slot], widths[slot] = raster(chr(cp))
        codepage.append((cp, slot))

    # Compose the 1024x32 atlas (4bpp), then write TIM (256x32 words).
    W, H = 1024, 32
    grid = [[0]*W for _ in range(H)]
    for i, lv in enumerate(levels):
        if lv is None:
            continue
        u, iy = slot_uv(i)
        for y in range(GLYPH_H):
            for x in range(GLYPH_W):
                grid[iy+y][u+x] = lv[y][x]
    pix = bytearray()
    for y in range(H):
        for xw in range(W//4):
            w = 0
            for n in range(4):
                w |= (grid[y][xw*4+n] & 0xF) << (n*4)
            pix += struct.pack('<H', w)
    body = bytearray()
    body += struct.pack('<I', 0x10) + struct.pack('<I', 0x08)
    body += struct.pack('<I', 12+32) + struct.pack('<HHHH', 0, 0, 16, 1) + load_clut()
    body += struct.pack('<I', 12+len(pix)) + struct.pack('<HHHH', 0, 0, W//4, H) + bytes(pix)
    out_tim = os.path.join(REPO, "pc_port", "Assets", "font", "Font16Unified.tim")
    os.makedirs(os.path.dirname(out_tim), exist_ok=True)
    open(out_tim, "wb").write(body)

    # Header: widths + code point -> slot map.
    lines = ["#ifndef PC_GLYPHMAP_H", "#define PC_GLYPHMAP_H", "",
             "/* Generated by pc_port/tools/build_unified_font.py — do not edit. */",
             "/* Base slots 0..83 = ASCII ('..z); 84+ = extended (accents/Cyrillic). */", "",
             f"#define GLYPH_EXT_BASE {EXT_BASE}",
             "static const unsigned char GLYPH_WIDTHS[168] = {"]
    for i in range(0, 168, 12):
        lines.append("    " + ", ".join(str(w) for w in widths[i:i+12]) + ",")
    lines += ["};", "",
              "typedef struct { unsigned short cp; unsigned char slot; } s_GlyphMap;",
              "static const s_GlyphMap GLYPH_MAP[] = {"]
    for cp, slot in codepage:
        lines.append(f"    {{ 0x{cp:04X}, {slot} }},")
    lines += ["};", "",
              f"#define GLYPH_MAP_COUNT {len(codepage)}", "", "#endif"]
    open(os.path.join(REPO, "pc_port", "include", "pc_glyphmap.h"), "w",
         encoding="utf-8").write("\n".join(lines) + "\n")

    # Preview.
    pal = []
    clut = load_clut()
    for i in range(16):
        w = struct.unpack('<H', clut[i*2:i*2+2])[0]
        pal.append((((w & 31) << 3), (((w >> 5) & 31) << 3), (((w >> 10) & 31) << 3)))
    img = Image.new("RGB", (W, H))
    for y in range(H):
        for x in range(W):
            img.putpixel((x, y), pal[grid[y][x]])
    img.resize((W*2, H*2), Image.NEAREST).save(os.path.join(scratch(), "unified_font_preview.png"))

    print(f"[unified] base=84  extended={len(codepage)} (cps: "
          + " ".join(chr(c) for c, _ in codepage[:20]) + (" ..." if len(codepage) > 20 else "") + ")")
    print(f"[unified] wrote Font16Unified.tim + pc_glyphmap.h")

if __name__ == "__main__":
    main()
